### ISSUE TITLE
Does this application supports push notifications & background job functionality

### ISSUE THREAD

**Issue by gowridev** [Erudika/para#50]
Does this application supports push notifications & background job functionality like parse server. Are these features part of your road map. could you please suggest third party libraries(for push notification & job scheduler) which work well with this application. Apple company is one your client, written in web site, there is mention of applie tvOS and OSX. Does this application support these as well?

**Comment by albogdano** [comment]
These features were left out intentionally because they are present in every cloud environment. I think any push service should work with Para. As for the Swift client library, it has been tested with Swift 4 on iOS, but I don't have access to tvOS or watchOS platforms so I'm not sure about those. If you find bugs in it, please report them at https://github.com/Erudika/para-client-ios/issues
